import type { Policy } from "./schema";

/**
 * Baseline policy shipped with the extension.
 * All rules here are well-tested and conservative — they prefer precision over recall.
 */
export const DEFAULT_POLICY: Policy = {
  version: 1,
  baseline: [
    // ── API Keys ──────────────────────────────────────────────────────────────
    {
      id: "openai-api-key",
      name: "OpenAI API Key",
      description: "Detects OpenAI API keys (sk-...)",
      severity: "critical",
      action: "block",
      enabled: true,
      tags: ["api-key", "openai"],
      kind: "pattern",
      pattern: "sk-[A-Za-z0-9_\\-]{20,}",
      flags: "",
      validator: "none",
      scope: "all",
    },
    {
      id: "openai-project-key",
      name: "OpenAI Project Key",
      description: "Detects OpenAI project-scoped API keys (sk-proj-...)",
      severity: "critical",
      action: "block",
      enabled: true,
      tags: ["api-key", "openai"],
      kind: "pattern",
      pattern: "sk-proj-[A-Za-z0-9_\\-]{20,}",
      flags: "",
      validator: "none",
      scope: "all",
    },
    {
      id: "anthropic-api-key",
      name: "Anthropic API Key",
      description: "Detects Anthropic Claude API keys (sk-ant-...)",
      severity: "critical",
      action: "block",
      enabled: true,
      tags: ["api-key", "anthropic"],
      kind: "pattern",
      pattern: "sk-ant-[A-Za-z0-9_\\-]{20,}",
      flags: "",
      validator: "none",
      scope: "all",
    },
    {
      id: "aws-access-key",
      name: "AWS Access Key ID",
      description: "Detects AWS access key IDs (AKIA/ASIA prefix)",
      severity: "critical",
      action: "block",
      enabled: true,
      tags: ["api-key", "aws"],
      kind: "pattern",
      pattern: "(AKIA|ASIA)[0-9A-Z]{16}",
      flags: "",
      validator: "none",
      scope: "all",
    },
    {
      id: "github-token",
      name: "GitHub Token",
      description: "Detects GitHub personal access tokens and OAuth tokens",
      severity: "critical",
      action: "block",
      enabled: true,
      tags: ["api-key", "github"],
      kind: "pattern",
      pattern: "gh[pousr]_[A-Za-z0-9]{36,}",
      flags: "",
      validator: "none",
      scope: "all",
    },
    {
      id: "slack-token",
      name: "Slack Token",
      description: "Detects Slack API tokens (xox*)",
      severity: "high",
      action: "block",
      enabled: true,
      tags: ["api-key", "slack"],
      kind: "pattern",
      pattern: "xox[abprs]-[0-9A-Za-z\\-]{10,}",
      flags: "",
      validator: "none",
      scope: "all",
    },
    {
      id: "google-api-key",
      name: "Google API Key",
      description: "Detects Google Cloud API keys (AIza...)",
      severity: "high",
      action: "block",
      enabled: true,
      tags: ["api-key", "google"],
      kind: "pattern",
      pattern: "AIza[0-9A-Za-z_\\-]{35}",
      flags: "",
      validator: "none",
      scope: "all",
    },
    {
      id: "stripe-live-secret-key",
      name: "Stripe Live Secret Key",
      description: "Detects Stripe live secret API keys (sk_live_...)",
      severity: "critical",
      action: "block",
      enabled: true,
      tags: ["api-key", "stripe", "financial"],
      kind: "pattern",
      pattern: "sk_live_[0-9a-zA-Z]{24,}",
      flags: "",
      validator: "none",
      scope: "all",
    },
    {
      id: "huggingface-token",
      name: "HuggingFace API Token",
      description: "Detects HuggingFace user access tokens (hf_...)",
      severity: "high",
      action: "block",
      enabled: true,
      tags: ["api-key", "huggingface", "ml"],
      kind: "pattern",
      pattern: "hf_[A-Za-z0-9]{34,}",
      flags: "",
      validator: "none",
      scope: "all",
    },
    {
      id: "npm-token",
      name: "npm Access Token",
      description: "Detects npm access tokens (npm_...)",
      severity: "high",
      action: "block",
      enabled: true,
      tags: ["api-key", "npm", "supply-chain"],
      kind: "pattern",
      pattern: "npm_[A-Za-z0-9]{36,}",
      flags: "",
      validator: "none",
      scope: "all",
    },
    {
      id: "azure-connection-string",
      name: "Azure Storage Connection String",
      description: "Detects Azure storage account connection strings",
      severity: "critical",
      action: "block",
      enabled: true,
      tags: ["api-key", "azure", "cloud"],
      kind: "pattern",
      pattern: "DefaultEndpointsProtocol=https?;AccountName=[^;]+;AccountKey=[A-Za-z0-9+/=]{44,}",
      flags: "i",
      validator: "none",
      scope: "all",
    },
    // ── Credentials ───────────────────────────────────────────────────────────
    {
      id: "pem-private-key",
      name: "PEM Private Key",
      description: "Detects PEM-encoded private key blocks",
      severity: "critical",
      action: "block",
      enabled: true,
      tags: ["credentials", "pem"],
      kind: "pattern",
      pattern: "-----BEGIN [A-Z ]*PRIVATE KEY-----",
      flags: "",
      validator: "none",
      scope: "all",
    },
    {
      id: "ssh-private-key",
      name: "SSH Private Key",
      description: "Detects OpenSSH private keys",
      severity: "critical",
      action: "block",
      enabled: true,
      tags: ["credentials", "ssh"],
      kind: "pattern",
      pattern: "-----BEGIN OPENSSH PRIVATE KEY-----",
      flags: "",
      validator: "none",
      scope: "all",
    },
    {
      id: "jwt-token",
      name: "JWT Token",
      description: "Detects JSON Web Tokens",
      severity: "high",
      action: "warn",
      enabled: true,
      tags: ["credentials", "jwt"],
      kind: "pattern",
      pattern: "eyJ[A-Za-z0-9_\\-]+\\.eyJ[A-Za-z0-9_\\-]+\\.[A-Za-z0-9_\\-]+",
      flags: "",
      validator: "none",
      scope: "all",
    },
    {
      id: "dotenv-line",
      name: ".env Assignment",
      description: "Detects .env-style KEY=VALUE lines with secret-like values",
      severity: "medium",
      action: "warn",
      enabled: true,
      tags: ["credentials", "env"],
      kind: "pattern",
      // Restrict the value charset to secret-like characters (base64/hex/alphanum with
      // special chars) and require ≥16 chars. This avoids false positives on common
      // env vars like NODE_ENV=production, LOG_LEVEL=INFO, PATH=/usr/bin, etc.
      pattern: "\\b[A-Z][A-Z0-9_]*=[A-Za-z0-9+/=_\\-]{16,}",
      flags: "m",
      validator: "none",
      scope: "outside_code",
    },
    {
      id: "db-connection-string",
      name: "Database Connection String",
      description: "Detects database URLs with embedded credentials",
      severity: "critical",
      action: "block",
      enabled: true,
      tags: ["credentials", "database"],
      kind: "pattern",
      // Matches scheme://user:password@host/db — requires ≥6 chars in the password segment
      pattern: "[a-zA-Z][a-zA-Z0-9+\\-.]*://[^:@\\s]+:[^@\\s]{6,}@[^\\s/]+",
      flags: "",
      validator: "none",
      scope: "all",
    },
    // ── PII ───────────────────────────────────────────────────────────────────
    {
      id: "credit-card",
      name: "Credit Card Number",
      description: "Detects credit card numbers using Luhn validation",
      severity: "critical",
      action: "block",
      enabled: true,
      tags: ["pii", "financial"],
      kind: "pattern",
      // Each brand alternative is "fixed literal prefix" + "(optional
      // separator)(digit), repeated" instead of a bare digit run — a plain
      // \d{n} run never matches how people actually type/paste card numbers
      // (spaces or hyphens every 4 digits, e.g. "4111 1111 1111 1111"),
      // so the old pattern silently let every human-formatted card through
      // undetected. luhnCheck() strips non-digits before validating, so
      // allowing the separator anywhere between digits doesn't weaken the
      // Luhn check — it just stops requiring a compact run to match at all.
      pattern:
        "\\b(?:4(?:[\\s-]?[0-9]){12}(?:(?:[\\s-]?[0-9]){3})?|[25][1-7](?:[\\s-]?[0-9]){14}|6(?:011|5[0-9][0-9])(?:[\\s-]?[0-9]){12}|3[47](?:[\\s-]?[0-9]){13}|3(?:0[0-5]|[68][0-9])(?:[\\s-]?[0-9]){11}|(?:2131|1800)(?:[\\s-]?[0-9]){11}|35(?:[\\s-]?[0-9]){14})\\b",
      flags: "",
      validator: "luhn",
      scope: "all",
    },
    {
      id: "us-ssn",
      name: "US Social Security Number",
      description: "Detects US SSNs in NNN-NN-NNNN format",
      severity: "critical",
      action: "block",
      enabled: true,
      tags: ["pii", "ssn"],
      kind: "pattern",
      pattern: "\\b\\d{3}-\\d{2}-\\d{4}\\b",
      flags: "",
      validator: "ssn",
      scope: "all",
    },
    // ── Network ───────────────────────────────────────────────────────────────
    {
      id: "rfc1918-ip",
      name: "Internal IP Address",
      description: "Detects RFC 1918 private IP addresses",
      severity: "medium",
      action: "warn",
      enabled: true,
      tags: ["network", "internal"],
      kind: "pattern",
      pattern:
        "\\b(10\\.|172\\.(1[6-9]|2\\d|3[01])\\.|192\\.168\\.)\\d{1,3}\\.\\d{1,3}\\b",
      flags: "",
      validator: "none",
      scope: "all",
    },
    {
      id: "ipv6-ula",
      name: "IPv6 Internal Address",
      description: "Detects IPv6 ULA (fc00::/7) and link-local (fe80::/10) addresses",
      severity: "medium",
      action: "warn",
      enabled: true,
      tags: ["network", "internal", "ipv6"],
      kind: "pattern",
      pattern: "\\b(fc[0-9a-f]{2}:|fd[0-9a-f]{2}:|fe80:)[0-9a-f:]+\\b",
      flags: "i",
      validator: "none",
      scope: "all",
    },
    {
      id: "aws-metadata-endpoint",
      name: "AWS/GCP/Azure Metadata Endpoint",
      description: "Detects cloud instance metadata service IP (169.254.169.254)",
      severity: "high",
      action: "warn",
      enabled: true,
      tags: ["network", "cloud", "ssrf"],
      kind: "pattern",
      pattern: "169\\.254\\.169\\.254",
      flags: "",
      validator: "none",
      scope: "all",
    },
    {
      id: "internal-hostname",
      name: "Internal Hostname",
      description: "Detects hostnames with internal TLDs (.internal, .corp, .local)",
      severity: "medium",
      action: "warn",
      enabled: true,
      tags: ["network", "internal"],
      kind: "pattern",
      pattern: "\\b[a-z0-9][a-z0-9\\-]*\\.(internal|corp|local|intra|lan)\\b",
      flags: "i",
      validator: "none",
      scope: "all",
    },
    // ── Entropy ───────────────────────────────────────────────────────────────
    {
      id: "high-entropy-token",
      name: "High-Entropy Token",
      description: "Detects long tokens with high Shannon entropy (potential secrets)",
      severity: "medium",
      action: "warn",
      enabled: true,
      tags: ["entropy", "secret"],
      kind: "entropy",
      minTokenLength: 24,
      // Raised from 4.0 → 4.5 to reduce false positives on long English words,
      // CamelCase identifiers, and compound variable names in pasted code.
      minBitsPerChar: 4.5,
    },
  ],
  custom: [
    // ── Layer 3 Dictionary — baseline classification labels ────────────────────
    {
      id: "classification-labels",
      name: "Document Classification Label",
      description:
        "Detects documents marked with classification labels (CONFIDENTIAL, SECRET, etc.)",
      severity: "high",
      action: "warn",
      enabled: true,
      tags: ["dictionary", "classification"],
      kind: "dictionary",
      terms: [
        "CONFIDENTIAL",
        "SECRET",
        "TOP SECRET",
        "RESTRICTED",
        "FOR INTERNAL USE ONLY",
        "PROPRIETARY",
        "DO NOT DISTRIBUTE",
        "NDA",
      ],
      caseSensitive: true,
    },
    {
      id: "legal-privilege-markers",
      name: "Legal Privilege Marker",
      description:
        "Detects attorney-client privilege and work product markers",
      severity: "high",
      action: "warn",
      enabled: true,
      tags: ["dictionary", "legal"],
      kind: "dictionary",
      terms: [
        "ATTORNEY-CLIENT PRIVILEGE",
        "ATTORNEY CLIENT PRIVILEGE",
        "PRIVILEGED AND CONFIDENTIAL",
        "ATTORNEY WORK PRODUCT",
      ],
      caseSensitive: false,
    },
  ],
  perSite: {
    "chatgpt.com": { enabled: true },
    "chat.openai.com": { enabled: true },
    "claude.ai": { enabled: true },
    "gemini.google.com": { enabled: true },
  },
  allowSendAnywayWithReason: true,
  auditRetentionDays: 30,
  failMode: "open",
};
