import type { Policy } from "./schema";

/**
 * Baseline policy shipped with the extension.
 * All rules here are well-tested and conservative — they prefer precision over recall.
 */
export const DEFAULT_POLICY: Policy = {
  version: 1,
  baseline: [
    // ── API Keys ──────────────────────────────────────────────────────────────
    {
      id: "openai-api-key",
      name: "OpenAI API Key",
      description: "Detects OpenAI API keys (sk-...)",
      severity: "critical",
      action: "block",
      enabled: true,
      tags: ["api-key", "openai"],
      kind: "pattern",
      pattern: "sk-[A-Za-z0-9_\\-]{20,}",
      flags: "",
      validator: "none",
      scope: "all",
    },
    {
      id: "openai-project-key",
      name: "OpenAI Project Key",
      description: "Detects OpenAI project-scoped API keys (sk-proj-...)",
      severity: "critical",
      action: "block",
      enabled: true,
      tags: ["api-key", "openai"],
      kind: "pattern",
      pattern: "sk-proj-[A-Za-z0-9_\\-]{20,}",
      flags: "",
      validator: "none",
      scope: "all",
    },
    {
      id: "anthropic-api-key",
      name: "Anthropic API Key",
      description: "Detects Anthropic Claude API keys (sk-ant-...)",
      severity: "critical",
      action: "block",
      enabled: true,
      tags: ["api-key", "anthropic"],
      kind: "pattern",
      pattern: "sk-ant-[A-Za-z0-9_\\-]{20,}",
      flags: "",
      validator: "none",
      scope: "all",
    },
    {
      id: "aws-access-key",
      name: "AWS Access Key ID",
      description: "Detects AWS access key IDs (AKIA/ASIA prefix)",
      severity: "critical",
      action: "block",
      enabled: true,
      tags: ["api-key", "aws"],
      kind: "pattern",
      pattern: "(AKIA|ASIA)[0-9A-Z]{16}",
      flags: "",
      validator: "none",
      scope: "all",
    },
    {
      id: "github-token",
      name: "GitHub Token",
      description: "Detects GitHub personal access tokens and OAuth tokens",
      severity: "critical",
      action: "block",
      enabled: true,
      tags: ["api-key", "github"],
      kind: "pattern",
      pattern: "gh[pousr]_[A-Za-z0-9]{36,}",
      flags: "",
      validator: "none",
      scope: "all",
    },
    {
      id: "slack-token",
      name: "Slack Token",
      description: "Detects Slack API tokens (xox*)",
      severity: "high",
      action: "block",
      enabled: true,
      tags: ["api-key", "slack"],
      kind: "pattern",
      pattern: "xox[abprs]-[0-9A-Za-z\\-]{10,}",
      flags: "",
      validator: "none",
      scope: "all",
    },
    {
      id: "google-api-key",
      name: "Google API Key",
      description: "Detects Google Cloud API keys (AIza...)",
      severity: "high",
      action: "block",
      enabled: true,
      tags: ["api-key", "google"],
      kind: "pattern",
      pattern: "AIza[0-9A-Za-z_\\-]{35}",
      flags: "",
      validator: "none",
      scope: "all",
    },
    // ── Credentials ───────────────────────────────────────────────────────────
    {
      id: "pem-private-key",
      name: "PEM Private Key",
      description: "Detects PEM-encoded private key blocks",
      severity: "critical",
      action: "block",
      enabled: true,
      tags: ["credentials", "pem"],
      kind: "pattern",
      pattern: "-----BEGIN [A-Z ]*PRIVATE KEY-----",
      flags: "",
      validator: "none",
      scope: "all",
    },
    {
      id: "ssh-private-key",
      name: "SSH Private Key",
      description: "Detects OpenSSH private keys",
      severity: "critical",
      action: "block",
      enabled: true,
      tags: ["credentials", "ssh"],
      kind: "pattern",
      pattern: "-----BEGIN OPENSSH PRIVATE KEY-----",
      flags: "",
      validator: "none",
      scope: "all",
    },
    {
      id: "jwt-token",
      name: "JWT Token",
      description: "Detects JSON Web Tokens",
      severity: "high",
      action: "warn",
      enabled: true,
      tags: ["credentials", "jwt"],
      kind: "pattern",
      pattern: "eyJ[A-Za-z0-9_\\-]+\\.eyJ[A-Za-z0-9_\\-]+\\.[A-Za-z0-9_\\-]+",
      flags: "",
      validator: "none",
      scope: "all",
    },
    {
      id: "dotenv-line",
      name: ".env Assignment",
      description: "Detects .env-style KEY=VALUE lines with high-entropy values",
      severity: "medium",
      action: "warn",
      enabled: true,
      tags: ["credentials", "env"],
      kind: "pattern",
      pattern: "\\b[A-Z][A-Z0-9_]*=\\S{8,}",
      flags: "m",
      validator: "none",
      scope: "outside_code",
    },
    // ── PII ───────────────────────────────────────────────────────────────────
    {
      id: "credit-card",
      name: "Credit Card Number",
      description: "Detects credit card numbers using Luhn validation",
      severity: "critical",
      action: "block",
      enabled: true,
      tags: ["pii", "financial"],
      kind: "pattern",
      pattern:
        "\\b(?:4[0-9]{12}(?:[0-9]{3})?|[25][1-7][0-9]{14}|6(?:011|5[0-9][0-9])[0-9]{12}|3[47][0-9]{13}|3(?:0[0-5]|[68][0-9])[0-9]{11}|(?:2131|1800|35\\d{3})\\d{11})\\b",
      flags: "",
      validator: "luhn",
      scope: "all",
    },
    {
      id: "us-ssn",
      name: "US Social Security Number",
      description: "Detects US SSNs in NNN-NN-NNNN format",
      severity: "critical",
      action: "block",
      enabled: true,
      tags: ["pii", "ssn"],
      kind: "pattern",
      pattern: "\\b\\d{3}-\\d{2}-\\d{4}\\b",
      flags: "",
      validator: "ssn",
      scope: "all",
    },
    // ── Network ───────────────────────────────────────────────────────────────
    {
      id: "rfc1918-ip",
      name: "Internal IP Address",
      description: "Detects RFC 1918 private IP addresses",
      severity: "medium",
      action: "warn",
      enabled: true,
      tags: ["network", "internal"],
      kind: "pattern",
      pattern:
        "\\b(10\\.|172\\.(1[6-9]|2\\d|3[01])\\.|192\\.168\\.)\\d{1,3}\\.\\d{1,3}\\b",
      flags: "",
      validator: "none",
      scope: "all",
    },
    // ── Entropy ───────────────────────────────────────────────────────────────
    {
      id: "high-entropy-token",
      name: "High-Entropy Token",
      description: "Detects long tokens with high Shannon entropy (potential secrets)",
      severity: "medium",
      action: "warn",
      enabled: true,
      tags: ["entropy", "secret"],
      kind: "entropy",
      minTokenLength: 24,
      minBitsPerChar: 4.0,
    },
  ],
  custom: [],
  perSite: {
    "chatgpt.com": { enabled: true },
    "chat.openai.com": { enabled: true },
    "claude.ai": { enabled: true },
    "gemini.google.com": { enabled: true },
  },
  allowSendAnywayWithReason: true,
  auditRetentionDays: 30,
};
